package vista;

import controller.UsuarioController;
import modelo.Genero;
import modelo.Usuario;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author Pablo
 */
public class Registro extends javax.swing.JDialog {

    public Registro(){
        initComponents();
        transparenteValidation();
        
        ValidationGroup group = validationPanel1.getValidationGroup();
        
        group.add(Usuario, StringValidators.REQUIRE_NON_EMPTY_STRING,StringValidators.NO_WHITESPACE);
        group.add(Contraseña,StringValidators.REQUIRE_NON_EMPTY_STRING , StringValidators.REQUIRE_VALID_INTEGER);
        group.add(RepetirContraseña,StringValidators.REQUIRE_NON_EMPTY_STRING , StringValidators.REQUIRE_VALID_INTEGER);
        group.add(Nombre, StringValidators.REQUIRE_NON_EMPTY_STRING,StringValidators.NO_WHITESPACE);
        group.add(Apellidos, StringValidators.REQUIRE_NON_EMPTY_STRING);
        
        
        
        
        
        validationPanel1.addChangeListener(new ChangeListener(){
            @Override
            public void stateChanged(ChangeEvent e) {
                if(validationPanel1.getProblem()== null){
                    Niño.setEnabled(true);
                    Niña.setEnabled(true);
                }else{
                    Niño.setEnabled(false);
                    Niña.setEnabled(false);
                }
                
            }
            
        
            });
        
    }
    
    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
   
    

  
    public void transparenteValidation(){
       validationPanel1.setOpaque(false);

     }
    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        Contraseña = new javax.swing.JTextField();
        Usuario = new javax.swing.JTextField();
        RepetirContraseña = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Apellidos = new javax.swing.JTextField();
        FondoRegistro = new javax.swing.JLabel();
        Niño = new javax.swing.JButton();
        Niña = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(validationPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 610, 60));

        Contraseña.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 340, 50));

        Usuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 340, 50));

        RepetirContraseña.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RepetirContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepetirContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(RepetirContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 340, 50));

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 340, 50));

        Apellidos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosActionPerformed(evt);
            }
        });
        jPanel1.add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 340, 50));

        FondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/fondoRegistroFinalFinal.png"))); // NOI18N
        jPanel1.add(FondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        Niño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NiñoActionPerformed(evt);
            }
        });
        jPanel1.add(Niño, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 90, 180));

        Niña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NiñaActionPerformed(evt);
            }
        });
        jPanel1.add(Niña, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 630, -1, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        
                
    }//GEN-LAST:event_UsuarioActionPerformed

    private void RepetirContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepetirContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepetirContraseñaActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidosActionPerformed

    private void NiñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NiñoActionPerformed
        
        Usuario u1 = new Usuario();
        
        u1.setId(0);
        u1.setUsuario(Usuario.getText());
        u1.setContraseña(Contraseña.getText());
        u1.setNombre(Nombre.getText());
        u1.setApellidos(Apellidos.getText());
        u1.setGenero(Genero.NIÑO);
        
        UsuarioController.createUsuario(u1);
        
        dispose();                                
    }//GEN-LAST:event_NiñoActionPerformed

    private void NiñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NiñaActionPerformed
        Usuario u1 = new Usuario();
        
        u1.setId(0);
        u1.setUsuario(Usuario.getText());
        u1.setContraseña(Contraseña.getText());
        u1.setNombre(Nombre.getText());
        u1.setApellidos(Apellidos.getText());
        u1.setGenero(Genero.NIÑA);
        
        UsuarioController.createUsuario(u1);
        
        dispose();
        
        
        
         
    }//GEN-LAST:event_NiñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registro dialog = new Registro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Apellidos;
    public javax.swing.JTextField Contraseña;
    private javax.swing.JLabel FondoRegistro;
    private javax.swing.JButton Niña;
    private javax.swing.JButton Niño;
    public javax.swing.JTextField Nombre;
    public javax.swing.JTextField RepetirContraseña;
    public javax.swing.JTextField Usuario;
    private javax.swing.JPanel jPanel1;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables
}
